### PR TITLE
add support for custom types that reads as []byte/[]uint8

### PR DESCRIPTION
**Pull request by jipiboily**

### CODE REVIEW

**Comment by jipiboily** [comment]
@fcat @gravis: Can I haz review?

**Comment by gravis** [comment]
https://play.golang.org/p/bafm9IOqJm should be enough ;)

**Comment by jipiboily** [comment]
This doesn't work, but as discussed on the chat, there is indeed a slightly better way. Updating.

**Comment by jipiboily** [comment]
@gravis updated.

**Review by gravis — APPROVED** [review]

**Pull request merged**
